#!/bin/sh -ex
# /etc/init.d/rpwc
#
# Written by Takashi Ando.
# Modified for monitoring garden.

### BEGIN INIT INFO
# Provides:          mathkernel
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mathkernel
### END INIT INFO

SCRIPTNAME=$0
DAEMON=/usr/local/bin/gunicorn

. /etc/default/rpwcweb

do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	${DAEMON} ${DAEMON_ARGS} || return 1
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	kill -TERM $(cat ${PID_FILE})
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PID_FILE
	return 0
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) echo Restarted ;;
			1) echo Failed to restart ;; # Old process is still running
			*) echo Failed to restart ;; # Failed to start
		esac
		;;
	  *)
		echo Failed to stop
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac
:
